from src.ai.gpt_processor import DocumentationData, ApiEndpoint
from src.utils.logger import logger

class MarkdownGenerator:
    @staticmethod
    def generate_markdown(data: DocumentationData) -> str:
        """
        Converts the structured API data into a professional Markdown document.
        """
        logger.info("Generatng Markdown documentation...")
        
        md_lines = []
        md_lines.append(f"# API Documentation\n")
        md_lines.append(f"Generated by Auto-Scraper on {data.endpoints[0].heading if data.endpoints else 'Unknown'}\n")
        md_lines.append("---\n")

        for endpoint in data.endpoints:
            md_lines.append(f"## {endpoint.heading}")
            md_lines.append(f"{endpoint.description}\n")
            
            # Request Section
            if endpoint.request:
                req = endpoint.request
                md_lines.append(f"### Request")
                md_lines.append(f"**Method:** `{req.method}`")
                md_lines.append(f"**Endpoint:** `{req.endpoint}`\n")
                
                if req.payload_sample:
                    md_lines.append("**Payload:**")
                    md_lines.append("```json")
                    md_lines.append(req.payload_sample) # It's already a JSON string
                    md_lines.append("```\n")

            # Parameters Section
            if endpoint.params:
                md_lines.append(f"### Parameters")
                md_lines.append("| Name | Type | Required | Description |")
                md_lines.append("|------|------|----------|-------------|")
                for param in endpoint.params:
                    req_str = "Yes" if param.required else "No"
                    md_lines.append(f"| `{param.name}` | `{param.type}` | {req_str} | {param.description} |")
                md_lines.append("\n")

            # Responses Section
            if endpoint.responses:
                md_lines.append(f"### Responses")
                for resp in endpoint.responses:
                    md_lines.append(f"**Status: {resp.status_code}** - {resp.description}")
                    if resp.body_sample:
                        md_lines.append("```json")
                        md_lines.append(resp.body_sample)
                        md_lines.append("```")
                    md_lines.append("\n")
            
            md_lines.append("---\n")

        return "\n".join(md_lines)

    @staticmethod
    def save_markdown(content: str, filename: str):
        with open(filename, "w", encoding="utf-8") as f:
            f.write(content)
        logger.success(f"📄 Markdown documentation saved to: {filename}")